### ISSUE TITLE
Should not have run against org 'tabulpdf'

### ISSUE THREAD

**Issue by hwine** [mozilla/Mozilla-GitHub-Standards#3]
@jeremybmerrill my apologies for spamming your project in tabulapdf/tabula/pull/1002 (and others)

Due to the project's past association with the Knight Mozilla Foundation, it was mistakenly listed as a Mozilla organization on [this wiki](https://wiki.mozilla.org/GitHub#Is_.22mozilla.22_the_only_github_.22organization.22_related_to_Mozilla.3F). I'll move that entry shortly.

**Comment by jeremybmerrill** [comment]
Thanks :) Not a big deal.
