### ISSUE TITLE
The bot open PRs with unsigned commits

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/Mozilla-GitHub-Standards#5]
On repositories that require signed commits to merge pull-requests, this makes it difficult to manage, since the PR cannot be accepted without changing the setting of all repositories, accepting PR, then changing back.

Additionally, when you own hundred of repositories, it would be a good option to provide a tool that can mass merge PRs (or mass cancel them so that the owner of the repos can merge on their own with the correct settings).

Right now for example I've to do this for about 70 repositories. It would have been much faster to have one issue asking for the missing file that is now required, than having to code a solution myself to remove the open PRs or manually going through each project

Note that if you plan to use this to update the file in the future for example, or require repositories to add more files, it would be worth just providing a script that will do this that repo or org owners can run themselves with elevated privileges so that the review process happens just once for all repos, instead of per repos

**Comment by jrconlin** [comment]
One of the other problems was that the bot was a little "over aggressive" in submitting PRs. I know several failed due to required CI systems failing because of the sudden load spike. I can only imagine that projects like circleCI and Travis weren't super happy with us. 

I agree that it would be better to have a bot either just file issues and maybe follow up with nag messages later. I'm very happy to add CoCs to projects or other standardization elements, but cleaning up the mess this PR made wasn't super fun.

**Comment by gdestuynder** [comment]
Here's a very crude script I made to "workaround" the issue for my repos in case that helps. It will basically remove restrictions and force merge.

https://gist.github.com/gdestuynder/73a6494afb7e9b300f73a76f2ec75684

**Comment by emmairwin** [comment]
Thanks for opening this, and brainstorming solutions.  I can say we did not anticipate that one person would own hundreds of repositories.  Can you share a bit about that with us?  Does this include those which are no longer active?   And do we have a process for archiving repos? This will be helpful information as well.

Thanks to you both, and appreciate that you understand we are learning as part of this first implementation of standards.

**Comment by jrconlin** [comment]
I can't speak for @gdestuynder-mozilla-owner, but I can speak for some of the issues with the Mass PR dump.

Most projects are handled by a team of individuals. OpSec has encouraged all projects under the Mozilla banner (so /mozilla/*, /mozilla-services/*, etc. ) to [follow mozilla standards](https://mana.mozilla.org/wiki/display/POLICIES/Standard%3A+GitHub+repositories+and+organizations), which generally are:
1) The "master" branch be protected from general updates
2) All PRs must be signed using stored keys
3) All PRs must be reviewed by at least one reviewer.
4) Even administrators are included in these.

Toss in that many of the Repos use automated CI/CD via free services like Travis and Circleci, and a mass PR deployment like this becomes a huge impact, which I don't believe was the goal of the exercise. 

As for archiving repos, that's actually something that is fairly new to github and mozilla. Previously, there were any number of ways that a given repo would be sunset, most often, it would just stop being updated. I've made some effort to use the new archival mechanism for github, but I can only do that for repos that I own or am an administrator on. It's probably high time for Devs to go over some of their older and probably forgotten repos and archive the ones that are no longer in active support, obsolete or just plain abandoned, but there's really been no incentive for folks to do so.

(Mind you, we're also still trying to work out the details for active services being sunset, so trying to get folks to deal with career detritus is far lower on the list.)

If nothing else, I think this exercise help highlight some things dev needs to consider more, so thank you.

**Comment by hwine** [comment]
I agree with all above -- we were too aggressive in the initial rollout. (I was hoping the GitHub rate limiting would be sufficient.)  We won't do that again.

Historically, there has not been (any?) resources put into managing the various GitHub orgs, so yeah, some of the orgs suffer the same problems as wikis. It's on the github-owners list of things to do to make some headway in that direction. But that's an all volunteer effort (except for security), so it's slow progress.

**Comment by hwine** [comment]
Re the "detecting repos where a PR causes more work" -- some of the items you called out are not detectable. 😦 (PR's & ideas welcome -- this script will be re-run every quarter or so.)

@jrconlin the standards you cite are only mandatory for services which deploy via cloud services, which make up a tiny fraction of all the repos. For the vast majority of repos, the PRs were taken "as is".

Which isn't to say we shouldn't do the work for future runs. Just that it's going to need to be based on heuristics, which folks like you will be in a better place to identify. I've opened #7 for that discussion - I'll need help.

**Comment by gdestuynder** [comment]
Regarding my use case, for context the organization is `mozilla-iam`.

We had a different set of rules than `mozilla`  when it was created, although right now they're fairly similar.
That said, we do own all the repos and in practice a single person (like me, and in many cases, just me) will go and manage them / fix them as necessary. Most of these repos also follow https://mana.mozilla.org/wiki/display/POLICIES/Standard%3A+GitHub+repositories+and+organizations or https://github.com/mozilla-iam/mozilla-iam/blob/master/GitHub-Security-Settings.md

In any case it's fixed by the above script I posted, because our main issue was that PRs would not merge due to the restrictions and I have chosen to override the restrictions for this one use case. Ideally -  signed commits would have helped - having a tool to mass review/allow too :) 

If we get further updates to these files, it would be good to have both in order to make this relatively painless

**Comment by hwine** [comment]
I've opened #9 to discuss options about signing. Brain power appreciated there as well. :)
